name: Build and Push Docker Image

on:
  workflow_dispatch:

env:
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: suwinet-simulator
  GITHUB_NAMESPACE: generiekzaakafhandelcomponent

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tagToDeploy: ${{ steps.prep.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: 'Generate unique docker tag to deploy'
        id: prep
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          SHORT_BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's/[\/+|<>,;-]//g')
          DATETIME=$(date "+%Y%m%d%H%M")
          BASE_VERSION=$(grep '^version\.semver=' version.properties | cut -d'=' -f2)
          SHA=${{ github.sha }}
          SEM_VERSION="${BASE_VERSION}-$DATETIME.${SHORT_BRANCH_NAME}.${SHA:0:8}"
          echo "image_tag=$SEM_VERSION" >> $GITHUB_OUTPUT

      - name: Unit test
        run: ./gradlew clean test

      - name: Build artifacts
        run: ./gradlew build

      - name: Archive build folder
        uses: actions/upload-artifact@v4
        with:
          name: suwinet-simulator-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Login to github packages'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: suwinet-simulator-build
          path: build/

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ needs.build.outputs.tagToDeploy }}
